wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: huggingface
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.7.16
    start_time: 1687841532
    t:
      1:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      - 80
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 63
      - 80
      3:
      - 13
      4: 3.7.16
      5: 0.12.21
      8:
      - 2
      - 5
