wandb_version: 1

T_max:
  desc: null
  value: 19
_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: huggingface
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.7.16
    start_time: 1687957793
    t:
      1:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      - 80
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 63
      - 80
      3:
      - 1
      - 13
      - 16
      4: 3.7.16
      5: 0.12.21
      8:
      - 2
      - 5
arch_name:
  desc: null
  value: tf_efficientnetv2_l.in21k
aux_loss:
  desc: null
  value: binary_cross_entropy
batch_size:
  desc: null
  value: 10
drop_path_rate:
  desc: null
  value: 0.1
drop_rate:
  desc: null
  value: 0.45
earlystop_patience:
  desc: null
  value: 5
epochs:
  desc: null
  value: 15
focal_alpha:
  desc: null
  value: 0.6
focal_gamma:
  desc: null
  value: 1.8
image_size:
  desc: null
  value: 640
loss1_coef:
  desc: null
  value: 1
loss_fn:
  desc: null
  value: FocalLoss
lr:
  desc: null
  value: 0.0001
n_worker:
  desc: null
  value: 8
optimizer:
  desc: null
  value: AdamW
save_path:
  desc: null
  value: model_640
scheduler:
  desc: null
  value: CosineAnnealingLR
scheduler_warmup:
  desc: null
  value: null
warmup_epo:
  desc: null
  value: 5
warmup_factor:
  desc: null
  value: 2
weight_decay:
  desc: null
  value: 0.002
