wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: true
    python_version: 3.7.16
    start_time: 1687780010
    t:
      1:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      - 80
      2:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      - 80
      3:
      - 2
      - 13
      - 16
      4: 3.7.16
      5: 0.12.21
      8:
      - 1
      - 2
      - 5
architecture:
  desc: null
  value: EfficientNetv2
aux_loss:
  desc: null
  value: binary_cross_entropy
batch_size:
  desc: null
  value: 64
dataset:
  desc: null
  value: SIIM-FISABIO-RSNA COVID-19 Detection
epochs:
  desc: null
  value: 20
learning_rate:
  desc: null
  value: 0.0001
loss_function:
  desc: null
  value: FocalLoss
optimizer:
  desc: null
  value: AdamW
